### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by jdavis-software**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### CODE REVIEW

**Comment by shellscape** [comment]
What's the difference between this one and #14 ?

**Comment by jdavis-software** [comment]
@shellscape just left a comment in the last one #14 and closed it. I resolved the last DOS security vulnerability in the (@acorn) package so now all packages up to date with no vulnerabilities.

**Comment by ankurk91** [comment]
Waiting for a release with webpack 5.x compatibility

**Comment by shellscape** [comment]
@jdavis-software I totally let this slip. Sorry about that. Would you be willing to give this a refresh? I have some time today to address it.

**Comment by shellscape** [comment]
Thanks for your work on this. I've resolved it in 597dd31 and credited you in the commit message.

**Pull request closed without merging**
